/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PssButton: typeof import('neat-ui')['_ButtonComponent']
    PssIcon: typeof import('neat-ui')['_IconComponent']
    PssPopup: typeof import('neat-ui')['_PopupComponent']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
